name: 'Build'

on: [push, pull_request]

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm ci --ignore-scripts

      - name: Lint
        run: npm run lint
